name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/cicd-docker-app || exit 1
            git pull origin main || exit 1
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            docker build -t cicd-docker-app .
            docker run -d -p 5000:5000 cicd-docker-app
          EOF    
